org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.3.27
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

jei_version=15.8.2.26

terrablender_version=3.0.1.10
terrablender_version_range=[3.0.0.169,)

mod_id=wildaside
mod_name=Wild Aside
mod_license=MIT
mod_version=2.2.0-1.20.1
mod_group_id=net.farkas.wildaside
mod_authors=Created by Erdei Farkas Gyula. New textures by CEntertain. Old textures by Farkas & Dylanvhs. Mucellith sounds by MSF. Special thanks to Dylanvhs, Toma400 & Lyof429.
mod_description=Wild Aside!